<?php

namespace Cabbuccino\ApiBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SearchApiController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Cabbuccino\ApiBundle\Controller\SearchApiController();
        return $instance;
    }
}
